
package apps;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MyService", targetNamespace = "http://service/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    apps.ObjectFactory.class
})
public interface MyService {


    /**
     * 
     * @param hai
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "ResponseMessage", partName = "ResponseMessage")
    @Action(input = "http://service/MyService/createRequest", output = "http://service/MyService/createResponse")
    public String create(
        @WebParam(name = "Hai", partName = "Hai")
        apps.Hai hai);

    /**
     * 
     * @return
     *     returns apps.ListHai
     */
    @WebMethod
    @WebResult(name = "ListHai", partName = "ListHai")
    @Action(input = "http://service/MyService/listRequest", output = "http://service/MyService/listResponse")
    public apps.ListHai list();

}
